import Head from "next/head";
import { AtSymbolIcon, HashtagIcon } from "@heroicons/react/solid";
import SubForum from "../components/SubForum";
import Layout from "../layout/Layout";
import Thread from "../components/Thread";

export default function Home() {
  return (
    <div>
      <Head>
        <title>naija wave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="  border flex flex-col sm:flex-row gap-10 pt-4 mb-5 sm:px-5">
        <div className="rounded-md text-xs mb-5 sm:h-screen sm:overflow-auto  border sm:w-64 divide-y-2 divide-gray-300   ">
          <SubForum />
        </div>
        <div className="flex-grow  flex flex-col  ">
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        <Thread/>
        </div>
        <div className=" h-52 bg-green-50 hidden sm:block">that my name</div>
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return( <Layout>{page}</Layout>);
};
