import Head from 'next/head'


export default function Home() {
  return (
    <div >
      <Head>
        <title>naija wave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=''>
      <h1>naija wave</h1>
      </div>
       
    </div>
  )
}
